name: "Deploy to VPS"
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        -   name: "Deploy to Cpanel via SSH"
            uses: "appleboy/ssh-action@v1.0.3"
            with:
                host: "144.24.154.232"
                username: "cicd"
                password: "RamboUmbo#69420"
                port: 22
                script: |
                    cd /var/www/html/EAPCI-Website
                    git pull
                    php artisan config:clear
                    php artisan route:clear
                    php artisan view:clear
                    composer install --optimize-autoloader --no-dev
                    php artisan key:generate
                    php artisan config:cache
                    php artisan route:cache
                    php artisan view:cache 
