name: "Deploy to VPS"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "SSH Login"
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_SECRET }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST }} > ~/.ssh/known_hosts
      - name: "Connect and pull"
        run: ssh cicd@144.24.154.232 "touch success.txt"
      - name: "Clean up"
        run: rm -rf ~/.ssh
